environment:
  matrix:
    - nodejs_version: "6"
    - nodejs_version: "4"

clone_depth: 1

branches:
  only:
  - master

version: "{build}"

install:
  - ps: Install-Product node $env:nodejs_version
  - npm -g install npm@latest
  - set PATH=%APPDATA%\npm;%PATH%
  - npm install

platform:
  - x86
  - x64

matrix:
  fast_finish: true

build: off

test_script:
  - node --version
  - npm --version
  - npm test
